export const navLinks = [
  {
    id: "home",
    path: "/",
    label: "Home",
    icon: "icon-home",
    href: "#home",
    isActive: true,
  },
  {
    id: "about",
    path: "/about",
    label: "About",
    icon: "icon-user-following",
    href: "#about",
  },
  {
    id: "services",
    path: "/services",
    label: "Services",
    icon: "icon-layers",
    href: "#services",
  },
  {
    id: "projects",
    path: "/projects",
    label: "Projects",
    icon: "icon-briefcase",
    href: "#projects",
  },
  {
    id: "contact",
    path: "/contact",
    label: "Contact",
    icon: "icon-bubble",
    href: "#testimonials",
  },
  {
    id: "contact",
    path: "/contact",
    label: "Contact",
    icon: "icon-note",
    href: "#contact",
  },
];
