export const navLinks = [
  {
    id: "home",
    path: "/",
    label: "Home",
    icon: "icon-home",
    href: "#home",
    isActive: true,
  },
  {
    id: "about",
    path: "/about",
    label: "About",
    icon: "icon-user-following",
    href: "#about",
  },
  {
    id: "services",
    path: "/services",
    label: "Services",
    icon: "icon-layers",
    href: "#services",
  },
  {
    id: "portfolio",
    path: "/portfolio",
    label: "Portfolio",
    icon: "icon-briefcase",
    href: "#portfolio",
  },
  {
    id: "testimonials",
    path: "/testimonials",
    label: "Testimonials",
    icon: "icon-bubble",
    href: "#testimonials",
  },
  {
    id: "contact",
    path: "/contact",
    label: "Contact",
    icon: "icon-note",
    href: "#contact",
  },
];
